### ISSUE TITLE
borrow: cleanup storybook

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1362] opened 2022-05-09 13:15 UTC
* rename "Wireframes" to "Protoypes"
* remove obsolete parts
* consilidate changes in app to stories
* snapshots:
  * disable for "wireframes"
  * document where and how its used
* check whether ES2020 features don't destroy the props docs anymore
* revive the docs tab in canvas mode
* minor: In story "Page Typology > Form" the search field's clear button does not appear (because it's uncontrolled)

**Comment by urs-van-binsbergen** [comment] 2022-06-14 09:19
What was done:

- Setup/config
  - Storybook minor update to 6.5.8
  - Command line flag `--no-open` (disable automatically opening a browser window when starting)
  - NPM install missing `@storybook/addon-docs` -> "Controls" tab in canvas mode works again
  - Fix warning about deprecated `/register` for two addons in `main.js` (means that the "a11y" tab works now)
  - Fix warning about deprecated `-s` command line flag (moved to `staticDirs` in `main.js`)
- Stories
  - Rename "Wireframes" to "Protoypes"
  - Rename "Integrated Components" to "Feature Components"
  - Consolidate changes in app to stories
  - Minor fix: In story "Page Typology > Form" the search field's clear button now works
- Components
  - Remove obsolete components (AppLayout, ModelFilterForm, ShoppingCart, TmpFilterBubblePanelSwitcher)
- Snapshots
  - Disable for "Prototypes" (fka "Wireframes")
  - Document where and how its used
  - Puppeteer not needed -> delete additional `package.config` for tests

Won't fix: 
- ES2020 features (e.g. `obj?.foo`) still will make the "arg table" break (the list of props and controls)
  - In "Docs" view the argtable does not show at all ("No inputs found for this component."). In "Canvas" view the "Controls" tab will display the controls as defined by the story's `args`/`argTypes`, but no metadata as defined by the component's `props` and `propTypes`
  - Tested with a freshly initialized cra + sb init with "essentials" plugins -> works!
  - Check: we have current versions of `react-scripts` and we use mainly its default config, so the issue is hard to explain. Not important enough.

**Closed as completed** 2022-06-20 14:56 UTC
Labels: accepted, new borrow, clean-up
