### ISSUE TITLE
Button missing when searching for name in global search

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#423] opened 2017-11-20 09:17 UTC
If you are reporting a bug or a problem with the deployment, then kindly use the following template:

#### Expected behaviour
I would expect to see a button "Show all found contracts" when searching for "Amos Bollag" in global search. 

#### Actual behaviour
The five last contracts are shown without displaying a button to navigate to older contracts. 

#### Steps to reproduce
1. go to pool Ausleihe Toni-Areal
2. search for "Amos Bollag" in global search
3. check section contracts --> button is missing

#### Specifications
- Leihs version: 4.8.0
- Browser version: safari 11.0

![bildschirmfoto 2017-11-20 um 10 14 34](https://user-images.githubusercontent.com/3356016/33017868-562e0548-cdf4-11e7-87d9-1dc1c7a7e98a.png)

**Comment by nadjaweisskopf** [comment] 2017-11-21 10:24
wait for matuss ticket with performance of global search

**Comment by eins78** [comment] 2017-11-28 10:25
I've analysed the problem (@phiku also had a look), and sursprinsingly the issue is caused by the way the SQL query is constructed in the model. In short, the ActiveRecord scope can't be counted using the default `#count` method anymore, which causes pagination helpers to deliver wrong results (the frontend gets the info that there is only 1 page, therefore no button shown).

This is best fixed by @nimaai, in the meantime I added a pending model spec that show the problem(s): https://github.com/leihs/leihs_legacy/blob/f6d90523e4643b44a7b159efbc3c6e69d3f583f2/spec/models/contract_spec.rb

**Closed** 2017-12-14 12:50 UTC
Labels: lending
