### ISSUE TITLE
Availability - don't calculate with a higher amount than available

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1502] opened 2023-01-24 14:58 UTC
#### Expected behaviour or future wish
If an amount of "7" has been entered in a model of an entitlement group but only 5 are available, Leihs should calculate with max. 5 and not 7. No matter if the lending dept. has solved the problem (in red) or not.

![grafik](https://user-images.githubusercontent.com/3356016/214327674-ace333ab-b363-435d-9589-8f00259b3f1e.png)

#### Issue or wish reported by
external school

#### Current behaviour
Leihs shows too many available items in Borrow. The system calculates with 7 instead of the max. available item amount of 5.

#### Steps to reproduce
1. check an the calender of an item in borrow which is listed in an entitlement group
2. go to manage section of the pool
3. edit the entitlement group and enter an amount which is higher than the max. lendable amount. 
4. save
5. go to borrow again and check the availability - it will be higher than the max. available one

#### Specifications
- Leihs version: 6.7.0
- Browser version: all
- MySQL/PostreSQL version:

**Comment by nimaai** [comment] 2023-02-15 11:53
@nadjaweisskopf So far I cannot reproduce it. I need more details.

**Comment by neoheat** [comment] 2023-03-23 13:59
Issue also in new timeline view 
<img width="1199" alt="timeline view" src="https://user-images.githubusercontent.com/123965725/227227103-a0487663-622b-4067-bb48-9a06121ad160.png">

tested with https://test.leihs.zhdk.ch/borrow/models/041c3d35-08f7-5cd8-802e-442502059da2?

**Comment by neoheat** [comment] 2023-03-23 14:14
Issue reproducable with https://test.leihs.zhdk.ch/borrow/models/3169c56f-139c-4496-81a9-bb909187bf22

**Comment by neoheat** [comment] 2023-03-24 10:01
With @nimaai tested. Wrong amount (3) displayed, only 2 available in park, just 1 is to borrow
https://test.leihs.zhdk.ch/borrow/models/129197e0-3394-5934-b62e-85c28482d14a

**Comment by nadjaweisskopf** [comment] 2023-03-30 07:16
@neoheat just had a chat with @urs-van-binsbergen about this ticket. The error handling in the entitlement groups should stay as it is. It's correct to highlight models, which have less availability then set in the number field. F.e. if an item has been retired and the new one has not arrived yet, the entitlement amount stays as it is until the new item is created in Leihs. 
BUT - we need to check if the availability calender should show the max. available amount instead of the entitled amount.

**Comment by neoheat** [comment] 2023-04-25 06:38
@nimaai I checked your fix in https://nimaai.ruby.zhdk.ch/ with Roger, which can be merged to Master. This is OK. For the refactoring of the different implementations, we must keep this in mind to address this when we update the manage section.

**Comment by nimaai** [comment] 2023-05-02 15:28
updated wiki: https://github.com/leihs/leihs/wiki/Availability/_compare/617e1f3175db4d8d2702ae95b49586d489b6519b...b56f21b9634d3d5086884cd4aaa733d834edf000

code: https://github.com/leihs/leihs/commit/78570f808a4c5ea6b920ae948fa6b57e788178fe

**Comment by nimaai** [comment] 2023-05-04 14:37
https://github.com/leihs/leihs/commit/82ceb31712b7bf841b23b96ff8212b636da167c3

**Closed** 2023-05-04 14:37 UTC
Labels: bug, lending

**Comment by neoheat** [comment] 2023-05-05 09:18
tested postive in test.leihs.zhdk.ch
