### ISSUE TITLE
leihs-zhdk-agw-auth finalizing

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#652] opened 2018-11-15 13:30 UTC
- AGW config 
    - clean up old AGW apps
    - new AGW correct config: URL-Regexes, URL-Examples, Adjust Titel etc

- publish repo, deployment/configuration
    - set correct base url

- make sure log in still works and uses/redirects to correct hostnames

**Comment by nadjaweisskopf** [comment] 2018-11-27 10:51
New AGW-instance for testing environment
Note: the current testing AGW-instance is used in prod!

**Comment by DrTom** [comment] 2018-11-28 15:21
Could not reproduce mentioned problems. 
AGW for test and staging done. 
closing

**Closed by DrTom** 2018-11-28 15:21 UTC
Labels: v5.0

**Comment by nadjaweisskopf** [comment] 2018-12-04 09:44
test login on staging and test
