### ISSUE TITLE
Transfer Data and Delete - cannot update view "entitlement_groups_users"

### ISSUE THREAD

**Issue by tmulzer** [leihs/leihs#1160] opened 2021-10-04 08:57 UTC
Transfer Data and Delete User throws a database-error.
Migrated from 5.3.1 to 6.2.2 yesterday. Now I'm trying to cleanup the users. One time yesterday "Transfer Data and Delete User" did work - with three users, leihs throws the database error below.

#### Expected behaviour
Delete User and transfer the locking foreign keys to the user, referenced in the target-user-uid field.

#### Actual behaviour
ERROR: cannot update view "entitlement_groups_users" Detail: Views containing GROUP BY are not automatically updatable. Hint: To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.

#### Steps to reproduce
- Open or navigate to https://leihs.innovisionlab.de/admin/users/<user_id>/delete
- Enter a valid user-id into the target-user-uid field.
- Click "Transfer and delete"

#### Related issues 
I didn't find related issues with keywords "delete user" or "transfer".

#### Specifications
- Leihs version: 6.2.2
- Browser version: Firefox 92
- MySQL/PostreSQL version: PSQL 13.4

**Comment by DrTom** [comment] 2021-10-04 19:13
Bug confirmed

**Comment by DrTom** [comment] 2021-10-06 08:46
Break down: in Leihs 5 entitlements were transferred when "transfer and delete user" was invoked. In Leihs 6 this does not work anymore because entitlements can be given via groups, too. A fix which behaves somewhat similar as in Leihs 5 would be quite involved. It would require some specification because it is not clear what should happen when the association comes via a group. Moreover, it would be confusing and counter intuitive to the administrator since all similar associations as roles, permissions, delegations etc are not transferred but removed. So the reasonable fix seems to be to remove entitlements, too.  Also: the special treatment of entitlements in leihs 5 was not described, nor documented or covered by tests.

**Comment by nadjaweisskopf** [comment] 2021-11-12 15:19
@DrTom if I transfer the user dcf42b83-8d7e-571e-b31d-21d4da69369e to f23ca963-a2d5-59db-bef8-9998ba40520d I get the following error: 

<img width="960" alt="Birkle_delete" src="https://user-images.githubusercontent.com/3356016/141490405-9b18bccf-1bf5-4507-9bb8-2ece68b5d1b0.png">

**Comment by eins78** [comment] 2021-11-15 17:23
@tmulzer Leihs 6.2.3 was released and includes a fix for this bug. Thanks for reporting!  https://github.com/leihs/leihs/releases/tag/6.2.3

**Closed by eins78** 2021-11-15 17:23 UTC
Labels: bug, admin
