### ISSUE TITLE
"Pool max items" too high for some models

### ISSUE THREAD

**Issue by urs-van-binsbergen** [leihs/leihs#1366] opened 2022-05-10 14:12 UTC
There is a package "6K-Videokamera Blackmagic Pocket Cinema (24-105mm)" in "Ausleihe Toni", where _pool max items_ is "1" according to new borrow although it is not borrowable and not findable in the catalog, and 404 in legacy. 
- URL in TEST, new borrow: https://test.leihs.zhdk.ch/app/borrow/models/dc6bcfaf-5b35-4717-a802-444edae7bc59
- URL in TEST, old borrow (404): https://test.leihs.zhdk.ch/borrow/models/dc6bcfaf-5b35-4717-a802-444edae7bc59

This is an inconsistency, but might not be a problem in practice. The user encounters this only if he has access to the package via a different pool (here: "AVS-Veranstaltungtechnik") or via a delegation. Then the dialog says that "Ausleihe Toni" has 1 item, while availability in the calendar is correctly shown as 0.

Guessing where this comes from: The package is marked "ausleihbar", but the contained items are not.

**Comment by urs-van-binsbergen** [comment] 2022-05-10 14:21
<img width="390" alt="start-end-date" src="https://user-images.githubusercontent.com/25439444/167651232-2118cb4b-2657-43ff-b27b-4132217356b9.png">

**Comment by neoheat** [comment] 2023-06-26 12:35
review @urs-van-binsbergen, @neoheat

**Comment by urs-van-binsbergen** [comment] 2023-06-27 12:49
@neoheat Probably this was fixed already: https://github.com/leihs/leihs/issues/1458

**Comment by neoheat** [comment] 2023-07-03 07:54
When the item is assigned to entitlement group `DFA - MFA`, only users of this group can see and order the item. Works as intended

**Closed by neoheat** 2023-07-03 07:54 UTC
Labels: bug, new borrow
