### ISSUE TITLE
Buggy behaviour when scrolling over menu

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#1469] opened 2022-10-31 09:15 UTC
#### Issue or wish reported by
NW - ITZ

#### Current behaviour
When moving up and down over the menu, without clicking anywhere, the menu points start to stay white --> see printscreen

#### Specifications
- Leihs version: 6.7.0
- Browser version: Firefox 102.4

![grafik](https://user-images.githubusercontent.com/3356016/198973463-0ff210af-ce33-45bf-be6f-4b3a64eb3c6c.png)

**Comment by urs-van-binsbergen** [comment] 2022-10-31 09:29
Not reproducible in Mac (even not with Citrix Windows env).
@nadjaweisskopf Can you reproduce it on Microsoft Edge?

**Comment by urs-van-binsbergen** [comment] 2022-11-01 07:55
@nadjaweisskopf Might be an issue with your specific setup? Since it also occurs with Github issue labels...

**Comment by urs-van-binsbergen** [comment] 2022-11-02 08:55
@nadjaweisskopf I tested on a Laptop (+/- same model, same setup like yours, newest Windows, newest Firefox version) and could not reproduce.

**Comment by nadjaweisskopf** [comment] 2022-11-03 10:09
@urs-van-binsbergen Ok, then I'll assign the ticket to my name and check again after the next update.

**Comment by nadjaweisskopf** [comment] 2023-06-19 20:39
I still have the same behaviour. @neoheat might want to test this issue with some ITZ employees - and if I'm the only one with this bug then let's close the ticket until we get similar feedbacks from users.

**Comment by neoheat** [comment] 2023-06-20 06:33
@nadjaweisskopf tested with several ITZ members. Issue could not be reproduced. Closing Issue.

**Closed by neoheat** 2023-06-20 06:33 UTC
Labels: bug, new borrow desktop
