### ISSUE TITLE
Calculation and display of Availability is buggy

### ISSUE THREAD

**Issue by nadjaweisskopf** [leihs/leihs#171] opened 2017-02-20 10:23 UTC

**Comment by nadjaweisskopf** [comment] 2017-02-20 13:30
http://leihs-v4-test.zhdk.ch/manage/8bd16d45-056d-5590-bc7f-12849f034351/contracts/submitted_3d677c34-3cde-523f-8e07-a3cd6faeafac_8bd16d45-056d-5590-bc7f-12849f034351_2017-02-20/edit

How to reproduce: 
1. Edit an order
2. Edit a model (go to calender) which has more than one item in total and more than one item available, for example "1/7"
3. Increase the mount inside the calender
4. Save
5. Check the amount on the model line. It has decreased.

**Comment by nimaai** [comment] 2017-02-23 19:02
@nadjaweisskopf I can not reproduce the problem for an order which I create. Can you?

Besides, this is a very hard problem to debug and understand. I need to have an up-to-date dump from both `test.leihs.zhdk.ch` and `test.leihs-v4.zhdk.ch` **FROM THE SAME DAY** (FYI @DrTom) and compare a particular order in a 1:1 manner to be able to see what changed in terms of availability data. 

Because by looking at our code changes I can't figure out if and how this problem got introduced (and what to speak of our green tests).

**Comment by nadjaweisskopf** [comment] 2017-02-27 08:18
@nimaai You're right, I can only reproduce this on orders which already exist. But we need to understand what happens, this is a major feature. We need to be 100% sure we do not have a bug. Can we have a look at this issue together today?

**Comment by nimaai** [comment] 2017-02-27 16:41
fixed by #172

**Closed by nimaai** 2017-02-27 16:41 UTC
Labels: bug, lending

**Comment by nadjaweisskopf** [comment] 2017-02-28 13:55
test ok!
